apiVersion: v1
kind: ConfigMap
metadata:
  name: totp-config
data:
  conf.yaml: |
    - username: mary
      secret: 3UFC3DUK27KESHBWEJDQS4B2HXLHGFZV
    - username: james
      secret: CV4JDXSYVFRJTHMNG4HUKF3OSTOP6B3H
    - username: test
      secret: DSENNVUPIDGLGIH5XE5F7EXPZIZAVZJH
