apiVersion: apps/v1
kind: Deployment
metadata:
  name: totp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: totp
  template:
    metadata:
      labels:
        app: totp
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 42000
        runAsGroup: 42000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: totp-users
          secret:
            secretName: totp-users
      containers:
      - name: totp
        image: uristmcdwarf/totp:latest
        args: ["serve"]
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 300Mi
        env:
        - name: PORT
          value: "8080"
        - name: USER_CONFIG
          value: "/config/conf.yaml"
        - name: JWT_KEY
          value: very-secret-key
        #valueFrom:
        #    secretKeyRef:
        #      name: totp_jwt_key
        #      key: key
        - name: CSRF_KEY
          value: another-secret-key
        # valueFrom:
        #    secretKeyRef:
        #      name: totp_csrf_key
        #      key: key
        # Env Vars you probably want to set
        #- name: OTEL_EXPORTER_OTLP_ENDPOINT -> open telemetry endpoint
        #- name: COOKIE -> name for cookie to use for JWT
        volumeMounts:
        - name: totp-users
          mountPath: "/config"
          readOnly: true
